#端口
server:
  port: 9200

#eureka注册中心地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

#服务名
spring:
  application:
    name: consumer-feign-server

#consumer-service:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
# feign中支持hystrix熔断降级
feign:
  hystrix:
    enabled: true


